### PR TITLE
color panel added; support version 1.5

### PR DESCRIPTION
**Pull request by nickolay-v**

### CODE REVIEW

**Comment by gfanton** [comment]
Hello @nickolay-v ,

Your PR looks ok, but i need you to fix some errors.

*ConvermaxAPI.php*:
+ I don't see any **```curl_close```** in your code, can you add it on each call of ```curl_init``` (or a unique init' in the constructor and a close in the destructor)
+ On L458 & L476, can you add some check to avoid a warning if jsonDecode fail to parse ```$data``` (ex: wrong url)
+ L264 ```pfsockopen``` should always be close with ```fclose``` at the end of the transaction.
+ L85,102,123,145,170,195,220,349,432 you don't have to unset since ```$data``` still in the function scope. garbage collector will do the job. (If you just want to silence unused variable error from PSR-2 use ```(unset)$data``` instead)

*Cron.php*:
+ L35 You need to use ```Module::getInstanceByName``` to instantiate Convermax.

Also indexing fail with a 404 response from *https://api.convermax.com/v2/...* .
Is *api.convermax.com/v2* the right url?

convermax

Regards.

**Comment by nickolay-v** [comment]
Hello @gfanton ,
We use pfsockopen to reuse same connection between script calls.

To use indexation user must sign up in our site, i remove connection form from main page.

**Comment by nickolay-v** [comment]
Hi, whats the status of this pull request?

**Comment by gfanton** [comment]
hello @nickolay-v 

Perfecto! I can now merge your PR :+1: :+1:
Oh and sorry for the delay..

Regards.

**Pull request merged**
